image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    # or with yarn:
    #- .yarn

stages:
  - build

before_script:
  - npm ci --cache .npm
  # or with yarn:
  #- yarn install --cache-folder .yarn

eas-build:
  stage: build
  script:
    - apk add --no-cache bash
    - npx cross-env EAS_NO_VCS=1 eas-cli build --platform all --non-interactive
