image: node:alpine

variables:
  EAS_NO_VCS: 1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    # or with yarn:
    #- .yarn

stages:
  - build

before_script:
  - npm ci --cache .npm
  # or with yarn:
  #- yarn install --cache-folder .yarn

eas-build-ios:
  stage: build
  script:
    - apk add --no-cache bash
    - npx eas-cli build --platform ios --non-interactive --auto-submit

eas-build-android:
  stage: build
  script:
    - apk add --no-cache bash
    - npx eas-cli build --platform android --non-interactive
